name: "Sphinx Pull Request Docs Check"
on:
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install myst-parser"
        run: pip install myst-parser

      - name: "Install book theme"
        run: pip install sphinx-book-theme

      - name: "Build Sphinx"
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./docs/"
          build-command: "python -m sphinx.cmd.build ./source/ ./build/"